=head1 NAME

CommonMark::GFM - Interface to the GitHub Flavored Markdown C library

=head1 SYNOPSIS

    use CommonMark::GFM;

    my $doc = CommonMark::GFM->parse(
        file  => $file,
        smart => 1,
    );

    my $html = CommonMark::GFM->markdown_to_html($markdown);
    my $doc  = CommonMark::GFM->parse_file($file);
    my $doc  = CommonMark::GFM->parse_document($markdown);
    my $doc  = CommonMark::GFM->create_document;

=head1 DESCRIPTION

This module is a wrapper around the official GitHub Flavored Markdown C library
L<I<libcmark-gfm>|https://github.com/github/cmark-gfm/>. It closely follows the
original API.

The main module provides some entry points to parse documents and convenience
functions for node creation. The bulk of features is available through
L<CommonMark::GFM::Node> objects of which the parse tree is made.
L<CommonMark::GFM::Iterator> is a useful class to walk through the nodes in a
tree. L<CommonMark::GFM::Parser> provides a push parser interface.

=head2 Installation

=head3 Installation of libcmark-gfm

Please note that the I<libcmark-gfm> API isn't stable yet. This version of the
Perl bindings is known to work with all releases between 0.21.0 and 0.31.1,
but there's no guarantee that it can be compiled with later versions. Also
note that upgrading a dynamically linked version of I<libcmark-gfm> may require
recompilation of the Perl distribution.

It is recommended to use the I<libcmark-gfm> packages provided by
recent Linux distros (Red Hat or CentOS don't have this library yet as
of this writing). On Debian or Ubuntu, run:

    sudo apt-get install libcmark-gfm-dev

On macOS using L<Homebrew|https://brew.sh>, run:

    brew install cmark-gfm

To install I<libcmark-gfm> from source:

    curl -LJO https://github.com/github/cmark-gfm/archive/0.29.0.gfm.13.tar.gz
    tar xzf cmark-gfm-0.29.0.gfm.13.tar.gz
    cd cmark-gfm-0.29.0
    make [INSTALL_PREFIX=/prefix]
    make test
    make install

See the I<libcmark-gfm> README for details.

=head3 Installation from a CPAN tarball

If I<libcmark-gfm> is in a standard location:

    perl Makefile.PL
    make
    make test
    make install

On macOS using Homebrew, specify the include and library locations:

    perl Makefile.PL \
        INC="-I$(brew --prefix)/include" \
        LIBS="-L$(brew --prefix)/lib -lcmark-gfm"
    make
    make test
    make install

Otherwise, specify the include and library locations:

    perl Makefile.PL \
        INC="-I/prefix/include" \
        LIBS="-L/prefix/lib -lcmark-gfm"
    make
    make test
    make install

See the documentation of I<ExtUtils::MakeMaker> for additional options.
The I<PERL_MM_OPT> environment variable is especially useful.

    export PERL_MM_OPT='INC="-I..." LIBS="-L... -lcmark-gfm"'

=head3 Build from a repository checkout

This distribution uses I<Dist::Zilla> with the external plugins
I<MakeMaker::Awesome> and I<CopyFilesFromBuild>. You can build and test with
I<dzil>:

    dzil test
    dzil build

The files generated by I<Dist::Zilla> are included in the repository,
so you can use the standard build process as well.

=head2 markdown_to_html

    my $html = CommonMark::GFM->markdown_to_html( $markdown, [$options] );

Converts a Markdown string to HTML. C<$options> is a bit field
containing the L<parse options|/Parser options> and
L<render options|CommonMark::GFM::Node/Render options> ORed together. It defaults
to zero (C<OPT_DEFAULT>).

This method is the equivalent to calling C<parse_document> and then
L<C<render_html>|CommonMark::GFM::Node/C<render_*>> on the resulting document,
or calling C<parse> and then L<C<render>|CommonMark::GFM::Node/C<render>>:

    my $html = CommonMark::GFM->markdown_to_html( $markdown );
    my $html = CommonMark::GFM->parse_document($markdown)->render_html;
    my $html = CommonMark::GFM->parse(string => $markdown)->render(format => 'html');

Equivalent calls with parser and rendering options, which can all be passed
to C<markdown_to_html()> but must be sent separately to the parse and render
methods:

    my $html = CommonMark::GFM->markdown_to_html(
        $markdown,
        OPT_UNSAFE | OPT_SMART,
    );

    my $html = CommonMark::GFM->parse_document(
        $markdown, OPT_SMART,
    )->render_html(OPT_UNSAFE);

    my $html = CommonMark::GFM->parse(
        string => $markdown,
        smart  => 1,
    )->render(
        format => 'html',
        unsafe => 1,
    );

=head2 parse

    my $doc = CommonMark::GFM->parse(
        string        => $string,
        normalize     => $bool,    # Optional
        smart         => $bool,    # Optional
        validate_utf8 => $bool,    # Optional
    );

    my $doc = CommonMark::GFM->parse(
        file          => $handle,
        normalize     => $bool,    # Optional
        smart         => $bool,    # Optional
        validate_utf8 => $bool,    # Optional
    );

Convenience function to parse documents. Exactly one of the C<string> or
C<file> options must be provided. When given a string, calls
L</parse_document>. When given a file, calls L</parse_file>. The remaining
options enable the respective L<parser options|/"Parser options">:

=over

=item * C<smart>

=item * C<validate_utf8>

=item * C<normalize> (no-op, deprecated)

=back

Returns the L<CommonMark::GFM::Node> of the root document.

=head2 parse_document

    my $doc = CommonMark::GFM->parse_document( $markdown, [$options] )

Parses a CommonMark::GFM document from a string returning the L<CommonMark::GFM::Node>
of the document root. C<$options> is a bit field containing the parser
options. It defaults to zero (C<OPT_DEFAULT>).

=head2 parse_file

    my $doc = CommonMark::GFM->parse_file( $file, [$options] );

Parses a CommonMark::GFM document from a file handle returning the
L<CommonMark::GFM::Node> of the document root. C<$options> is a bit field
containing the parser options. It defaults to zero (C<OPT_DEFAULT>).

=head2 Parser options

The parser and rendering options are a bit field created by ORing the
following constants:

    CommonMark::GFM::OPT_DEFAULT => 0
    CommonMark::GFM::OPT_NORMALIZE
    CommonMark::GFM::OPT_VALIDATE_UTF8
    CommonMark::GFM::OPT_SMART

Parser options can be imported from L<CommonMark::GFM> with tag C<opt>.

    use CommonMark::GFM qw(:opt);
    my $doc = CommonMark::GFM->parse_document(
        $markdown,
        OPT_SMART | OPT_VALIDATE_UTF8,
    );

=over

=item C<OPT_NORMALIZE>

Deprecated.  Makes sure that adjacent text nodes are merged in the
parse tree. This option has no effect with libcmark-gfm which always
normalizes text nodes.

=item C<OPT_SMART>

Enables the "smart quote" feature which turns vertical into typographic
quotation marks, double and triple hyphens into en and em dashes, and triple
periods into ellipses.

=item C<OPT_VALIDATE_UTF8>

Turns on UTF-8 validation. Normally, this shouldn't be necessary because Perl
strings should always contain valid UTF-8. But it is possible to create
strings flagged as UTF-8 that contain invalid UTF-8, for example with XS. The
option may be used if you don't trust the input data and want to make
absolutely sure that the output is valid UTF-8. If invalid bytes are found,
they are replaced with the Unicode replacement character C<U+FFFD>.

=back

=head2 Node creation

    my $document = CommonMark::GFM->create_document(
        children => \@children,
    );
    my $header = CommonMark::GFM->create_heading(
        level    => $level,
        children => \@children,
        text     => $literal,
    );
    my $paragraph = CommonMark::GFM->create_paragraph(
        children => \@children,
        text     => $literal,
    );
    my $block_quote = CommonMark::GFM->create_block_quote(
        children => \@children,
    );
    my $list = CommonMark::GFM->create_list(
        type     => $type,
        delim    => $delim,
        start    => $start,
        tight    => $tight,
        children => \@children,
    );
    my $item = CommonMark::GFM->create_item(
        children => \@children,
    );
    my $code_block = CommonMark::GFM->create_code_block(
        fence_info => $fence_info,
        literal    => $literal,
    );
    my $html = CommonMark::GFM->create_html_block(
        literal => $html,
    );
    my $custom_block = CommonMark::GFM->create_custom_block(
        on_enter => $raw_prefix,
        on_exit  => $raw_suffix,
        children => \@children,
        text     => $literal,
    );
    my $thematic_break = CommonMark::GFM->create_thematic_break;
    my $text = CommonMark::GFM->create_text(
        literal => $literal,
    );
    my $code = CommonMark::GFM->create_code(
        literal => $literal,
    );
    my $html_inline = CommonMark::GFM->create_html_inline(
        literal => $literal,
    );
    my $emph = CommonMark::GFM->create_emph(
        children => \@children,
        text     => $literal,
    );
    my $strong = CommonMark::GFM->create_strong(
        children => \@children,
        text     => $literal,
    );
    my $url = CommonMark::GFM->create_url(
        url      => $url,
        title    => $title,
        children => \@children,
        text     => $literal,
    );
    my $image = CommonMark::GFM->create_image(
        url      => $url,
        title    => $title,
        children => \@children,
        text     => $literal,
    );
    my $custom_inline = CommonMark::GFM->create_custom_inline(
        on_enter => $raw_prefix,
        on_exit  => $raw_suffix,
        children => \@children,
        text     => $literal,
    );
    my $softbreak = CommonMark::GFM->create_softbreak;
    my $linebreak = CommonMark::GFM->create_linebreak;

These convenience functions can be used to create nodes, set properties,
and add children in a single operation. All parameters are optional.

The C<children> parameter expects an arrayref of nodes to be added as
children. The special C<text> parameter adds a single text child with
literal C<$literal>. It can't be used together with C<children>. All other
parameters correspond to a node property.

=head2 libcmark-gfm version information

    my $version = CommonMark::GFM->version;
    my $string  = CommonMark::GFM->version_string;
    my $version = CommonMark::GFM->compile_time_version;
    my $string  = CommonMark::GFM->compile_time_version_string;

Return the version number or version string of libcmark-gfm, either the
library version linked against at run time or compile time.

=head1 COPYRIGHT

This software is copyright (C) by Nick Wellnhofer
and copyright (C) 2026 gemmaro.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
